### PR TITLE
Version 1 of BiciKlik - merge to main

### PR DESCRIPTION
**Pull request by OliverKreitmeyer**
This will be open but will only be closed during the tomorrows meeting if everyone allows the review. Please check the code one last time and say if something is incorrect or missing.

### CODE REVIEW

**Review by ante-i — APPROVED** [review]
Looks good; lets get this bread.

**Review by marinprusac — APPROVED** [review]
Awesome! Great work guys.

**Review by Moodax — APPROVED** [review]
bravo

**Comment by EWallIg** [comment]
nice

**Pull request merged**
